# modules/nvidia_ai.py

from typing import Dict, Any, List

class NvidiaAI:
    def explain_alert(self, alert: Dict[str, Any]) -> Dict[str, Any]:
        rule = alert.get("rule_name", "Unknown rule")
        severity = alert.get("severity", "unknown")
        user = alert.get("user") or "N/A"
        host = alert.get("host") or "N/A"
        
        base = f"This alert was generated by '{rule}' with severity {severity}."
        details = f"User {user} on host {host} triggered the condition."
        recs = [
            "Verify if the user activity is expected.",
            "Check recent logon locations and devices.",
            "If suspicious, disable the account and collect forensic artifacts.",
        ]
        
        return {
            "analysis": base + " " + details,
            "recommended_actions": recs,
            "email_summary": f"[{severity.upper()}] {rule} for {user} on {host}",
        }
